---

name: Create Release

on:
  push:
    branches: [ main ]
    # Sequence of patterns matched against refs/tags
    tags:        
      - 'v1.*' # Push events to matching v1*, i.e. v1.0, v20.15.10

permissions:
  issues: write
  pull-requests: read
  security-events: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - what up!!
          draft: false
          prerelease: true