name: GH-Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+.*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
      branches: [ main ]

  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt

      # - name: Create tag
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/v${{ env.version }}',
      #         sha: context.sha
      #       })

      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          created_tag: 'v${{ github.ref }}'
          #version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          release_text: What up, changes!!
          files: |
            ${{ github.workspace }}-CHANGELOG.txt
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}