name: Main

name: Adious-ado
on:
  push:
    branches: [ main ]
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  fork:
    branches: [ main ]        

permissions:
  issues: write
  pull-requests: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
      - name: Build
        run: echo ${{ github.sha }} > Release.txt        
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: nerds-run/odious-ado@v1.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE