name: Main

name: Adious-ado
on:
  push:
    branches: [ main ]
  fork:
    branches: [ main ]

permissions:
  issues: write
  pull-requests: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
      - name: Release
        uses: nerds-run/odious-ado@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE