name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    tags:
      - "v*"

permissions:
  issues: write
  pull-requests: read
  security-events: write      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ OS.ENV }}
      - name: Build
        run: echo ${{ github.sha }} > Release.txt        
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: nerds-run/odious-ado@v1.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE