---
name: Move Major Release Tag
# Whenever a new release is made, push a major version tag
on:
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  movetag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Get major version number and update tag
        run: |
          version=${GITHUB_REF#refs/tags/}
          major=${version%%.*}
          git config --global user.name 'blackcodeking912'
          git config --global user.email 'blackcodeking912@users.noreply.github.com'          
          git tag -fa ${major} -m "Update major version tag"
          git push origin ${major} --force