name: Auto Tag Release
on:
    push:
        branches: [ main ]

concurrency: production

permissions: write-all

jobs:
    Patch:
        runs-on: unbuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: '0'

            - name: Minor verison for each merge
              id: dryRunTag
              uses: anothrNick/github-tag-action@1.36.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                WITH_V: true
                DRY_RUN: true

            - name: New tag echo
              run: |
                echo "Next tag version number is: ${{steps.dryRunTag.outputs.new_tag}}"

            - name: Current tag echo
              run: |
                echo "Current tag version number is: ${{steps.dryRunTag.outputs.tag}}"
                
            - name: Current part incremented
              run: |
                echo "The version increment is: ${{steps.dryRunTag.outputs.part}}"

            - name: Minor verison for each merge
              id: finalRunTag
              uses: anothrNick/github-tag-action@1.36.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                WITH_V: true
            